import type { Metadata } from 'next'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function layout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabase=createServerComponentClient({cookies})
    const {data:{session}}=await supabase.auth.getSession()
    console.log(session)
    if(session){
        redirect("/")
    }
    
  return (
    <>
    {children}
    </>
  )
}
