import {ReactNode,FC} from 'react'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

interface layoutProps {
    children:ReactNode
}

const layout:FC<layoutProps>=({children})=>{
 return(
    <>
        <main
            className='p-2 md:container'
        >
            {children}
        </main>
    </>
)}

export default layout