import {ReactNode,FC} from 'react'
import type { Metadata } from 'next'
import Navbar from '@/components/Navbar'
import { getSession } from '../supabase-server'
import { redirect } from 'next/navigation'


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

interface layoutProps {
    children:ReactNode
}

const layout:FC<layoutProps>=async({children})=>{
    const session = await getSession()
      
    if (!session) {
        return redirect('/signIn');
    }
    
    
 return(
    <>
        <Navbar />
        {children}
    </>
)}

export default layout