import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './global.css'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const supabase=createServerComponentClient({cookies})
    const {data:{session}}=await supabase.auth.getSession()


    
  return (
    <html lang="en">
      <body className='dark'>
        {children}
        <Toaster/>
      </body>
    </html>
  )
}
